version: 2
registries:
  maven-repository-maven-pkg-github-com-bluedragonmc-messaging:
    type: maven-repository
    url: https://maven.pkg.github.com/BlueDragonMC/Messaging
    username: FluxCapacitor2
    password: "${{secrets.MAVEN_REPOSITORY_MAVEN_PKG_GITHUB_COM_BLUEDRAGONMC_MESSAGING_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  assignees:
  - FluxCapacitor2
  registries:
  - maven-repository-maven-pkg-github-com-bluedragonmc-messaging
